IN_PATH = "in/"
OUT_PATH = "out/"

DB_OUTFILE = OUT_PATH + "db-out.tsv"
DEX_OUTFILE = OUT_PATH + "dex-out.tsv"
GO_OUTFILE = OUT_PATH + "go-out.tsv"
DOKU_OUTFILE = OUT_PATH + "doku-out.tsv"
STATS_OUTFILE = OUT_PATH + "stats-out.tsv"
DOKU_STATS_OUTFILE = OUT_PATH + "doku_stats-out.tsv"

# Commands
ABILITIES_INFILE = IN_PATH + "abilities-in.tsv"
ABILITIES_OUTFILE = OUT_PATH + "abilities-out.tsv"
TYPES_INFILE = IN_PATH + "types-in.tsv"
TYPES_OUTFILE = OUT_PATH + "types-out.tsv"
REGIONS_OUTFILE = OUT_PATH + "regions-out.tsv"
FAMILIES_INFILE = IN_PATH + "families.in"
FAMILIES_OUTFILE = OUT_PATH + "families.out"
GENDER_INFILE = IN_PATH + "gender-in.tsv"
GENDER_OUTFILE = OUT_PATH + "gender-out.tsv"
CATCH_RATE_INFILE = IN_PATH + "catchrate-in.tsv"
CATCH_RATE_OUTFILE = OUT_PATH + "catchrate-out.tsv"
BABY_INFILE = IN_PATH + "baby.in"
FOSSIL_INFILE = IN_PATH + "fossil.in"
CATEGORY_OUTFILE = OUT_PATH + "category.out"
BALLS_OUTFILE = OUT_PATH + "balls.out"
GO_SHADOW_INFILE = IN_PATH + "go_shadow-in.tsv"
