FILE_PATH = "out/"

DB_OUTFILE = FILE_PATH + "db-out.tsv"
DEX_OUTFILE = FILE_PATH + "dex-out.tsv"
DOKU_OUTFILE = FILE_PATH + "doku-out.tsv"
STATS_OUTFILE = FILE_PATH + "stats-out.tsv"
DOKU_STATS_OUTFILE = FILE_PATH + "doku_stats-out.tsv"

# Commands
ABILITIES_INFILE = FILE_PATH + "abilities-in.tsv"
ABILITIES_OUTFILE = FILE_PATH + "abilities-out.tsv"
TYPES_INFILE = FILE_PATH + "types-in.tsv"
TYPES_OUTFILE = FILE_PATH + "types-out.tsv"
REGIONS_OUTFILE = FILE_PATH + "regions-out.tsv"
FAMILIES_INFILE = FILE_PATH + "families.in"
FAMILIES_OUTFILE = FILE_PATH + "families.out"
GENDER_INFILE = FILE_PATH + "gender-in.tsv"
GENDER_OUTFILE = FILE_PATH + "gender-out.tsv"
CATCH_RATE_INFILE = FILE_PATH + "catchrate-in.tsv"
CATCH_RATE_OUTFILE = FILE_PATH + "catchrate-out.tsv"
BALLS_OUTFILE = FILE_PATH + "balls.out"
